services:
  app:
    image: slackernews:latest
    build: .
    restart: unless-stopped

  anubis:
    image: ghcr.io/techarohq/anubis:latest
    restart: unless-stopped
    command: ["-target", "http://app:3000"]
    environment:
      POLICY_FNAME: /data/botPolicy.yaml
    volumes:
      - ./anubis/botPolicy.yaml:/data/botPolicy.yaml:ro
    depends_on:
      - app

  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "127.0.0.1:3006:80"
    volumes:
      - ./nginx/:/etc/nginx/
    depends_on:
      - anubis
